ALSA: compress : Fix return-type warning
* fix conflict after merged with https://github.com/zeta96/L_kernul_santoni/commit/524493decec1b332ce1e6a94ec7e660daf434fb1 , just remove ret: because it will be wunused after merged

../sound/core/compress_offload.c:742:1: error: control may reach end of non-void function [-Werror,-Wreturn-type]
}
^