random: Mark input_timer_state with __maybe_unused
Since we put static variable to a header file it's copied to each module
that includes the header. But not all of them are actually used it.

fix after pick https://github.com/zeta96/L_kernul_santoni/commit/2fe10a5f60f5a47899d4f0c159c478020778bec4#diff-8a7983688893b4a00f280f89e6e6c559 with __maybe_unused to calm a compiler down:

../drivers/char/random.c:1008:32: error: unused variable 'input_timer_state' [-Werror,-Wunused-variable]
static struct timer_rand_state input_timer_state = INIT_TIMER_RAND_STATE;